name: mplusanalyzer
description: "Mplus Analyzer"

publish_to: 'none'

version: 1.0.6

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  flutter_session_manager: ^1.0.3
  uuid: ^4.5.1
  crypto: ^3.0.3
  http: ^1.2.1
  date_format: ^2.0.7
  package_info_plus: ^8.0.0
  multi_dropdown: ^3.0.1
  jwt_decoder: ^2.0.1
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.1
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.3
  animated_tree_view: ^2.3.0
  image_picker: ^1.0.0
  flutter_image_compress: ^2.0.3
  flutter_image_compress_common: ^1.0.2
  pdf: ^3.11.1
  printing: ^5.13.4
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  fl_chart: ^1.1.0
  syncfusion_flutter_charts: ^31.1.17



dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: urbanist
      fonts:
        - asset: fonts/urbanist.ttf
    - family: poppins_medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: poppins_regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: poppins_semibold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: poppins_bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: poppins_light
      fonts:
        - asset: fonts/Poppins-Light.ttf

  assets:
    - assets/
    - assets/icons/
    - fonts/
