import 'global_params.dart';

class LanguagePack {
  Map<String, Map<String, String>> translations = {
    'az': {
      'userName': 'İstifadəçi',
      'password': 'Şifrə',
      'login': 'Daxil ol',
      'entry': 'Giriş',
      'version': 'Versiya',
      'successful': 'Uğurlu',
      'usernameOrPasswordIsIncorrect': 'İstifadəçi və ya şifrə yanlışdır!',
      'anErrorOccurred': 'Xəta baş verdi!',
      'loginMismatch': 'Giriş məlumatlarında uyğunsuzluq aşkarlandı!',
      'youDontHavePermission': 'İcazəniz yoxdur',
      'language': 'Dil',
      'logout': 'Sistemdən çıxış',
      'warning': 'Xəbərdarlıq',
      'ok': 'Oldu',
      'details': 'Təfərrüat',
      'attention': 'Diqqət!',
      'yes': 'Bəli',
      'no': 'Xeyr',
      'search': 'Axtar',
      'az': 'Azərbaycanca',
      'en': 'Ingiliscə',
      'ru': 'Rusca',
      'tr': 'Türkçe',
      'about': 'Haqqımızda',
      'close': 'Bağlamaq',
      'settings': 'Sazlamalar',
      'faq': 'Sorğu',
      'counting': 'Maşın sayım',
      'benchmark': 'Qiymət üzləşdirmə',
      'confront': 'Borc Üzləşdirmə',
      'operations': 'Əməliyyatlar',
      'code': 'Kodu',
      'name': 'Adı',
      'seller': 'Satıcı',
      'distance': 'Məsafə',
      'debt': 'Borc',
      'lastConfrontDate': 'Son üzləşmə',
      'list': 'Siyahı',
      'map': 'Xəritə',
      'all': 'Hamısı',
      'errorGettingLocation': 'Koordinatların təyin edilməsində xəta',
      'locationServicesAreDisabled':
          'Məkan xidməti deaktiv edilib. Zəhmət olmasa, aktivləşdirin',
      'locationPermissionsAreDenied': 'Məkan icazələri rədd edilib!',
      'locationPermissionsArePermanentlyDenied':
          'Məkan icazələri həmişəlik rədd edilib!',
      'areYouSureYouWantToSave': 'Yadda saxlamaq istədiyinizə əminsinizmi?',
      'route': 'Marşrut',
      'chaDocTypes1': 'Kasa Təhsilat Qəbzi',
      'chaDocTypes2': 'Kasa Ödəmə Qəbzi',
      'chaDocTypes3': 'Borc Dekontu',
      'chaDocTypes4': 'Alacaq Dekontu',
      'chaDocTypes5': 'Virman Dekontu',
      'chaDocTypes6': 'Kurs Fərqi',
      'chaDocTypes20': 'Gələn Köçürmə',
      'chaDocTypes21': 'Gondərilən Köçürmə',
      'chaDocTypes31': 'Alış Fakturası',
      'chaDocTypes32': 'Qaytarma Fakturası',
      'chaDocTypes33': 'Qaytarma Fakturası',
      'chaDocTypes37': 'Satış Fakturası',
      'chaDocTypes38': 'Satış Fakturası',
      'extra': 'Hərəkətlər',
      'total': 'Məbləğ',
      'discount': 'Endirim',
      'quantity': 'Miqdar',
      'price': 'Qiymət',
      'areYouSureYouWantToDeleteThat': 'Silmək istədiyinizə əminsinizmi?',
      'documentDeleted': 'Sənəd silindi!',
      'clientDebt': 'Borc',
      'confrontedDebt': 'Üzləşdirilmiş',
      'revise': 'Dəyişdir',
      'delete': 'Sil',
      'client': 'Müştəri',
      'clientExtra': 'Hərəkətləri',
      'clientConfronts': 'Üzləşmələri',
      'docNumber': 'Sənəd nömrəsi',
      'newConfront': 'Yeni üzləşmə',
      'isClientAgree': 'Müştərilə razılaşdırılıbmı?',
      'comment': 'Şərh',
      'chooseClient': 'Müştəri seç',
      'confrontTotal': 'Üzləşmə məbləği',
      'documentSaved': 'Sənəd saxlanıldı',
      'clientNotSelected': 'Müştəri seçilməyib!',
      'confrontDebtNotEntered': 'Üzləşmə məbləği daxil edilməyib!',
      'choose': 'Seç',
      'clientFilter': 'Müştəri filteri',
      'newFaq': 'Yeni sorğu',
      'questions': 'Suallar',
      'chooseFilter': 'Filter seç',
      'answer': 'Cavab',
      'addImages': 'Şəkil əlavə et',
      'takePhoto': 'Kamera',
      'galery': 'Qaleriya',
      'cancel': 'Ləğv et',
      'areYouSureYouWantToDeleteThisPhoto':
          'Bu şəkli silmək istədiyinizə əminsinizmi?',
      'theQuestionDoesNotExistForThisClient':
          'Bu müştəri üçün sual mövcud deyil!',
      'questionsMarkedWithStarCannotBeSkipped':
          '* ilə işarələnmiş suallar buraxılabilməz!',
      'print': 'Çap et',
      'newCounting': 'Yeni maşın sayım',
      'car': 'Maşın',
      'chooseCar': 'Maşın seç',
      'quantityTyped': 'Daxil edilən sayımlar:',
      'onSystem': 'Sistemdə olan:',
      'totalCounted': 'Yekun sayılan:',
      'counting_': 'Sayım',
      'items': 'Mallar',
      'subGroupless': 'Alt qrupsuz',
      'warehouseNotSelected': 'Anbar seçilməyib!',
      'noItemsOnList': 'Siyahıda mal yoxdur!',
      'clientNotFound': 'Müştəri tapılmadı!',
      'confrontShort': 'Üzləşmə',
      'type': 'Növ',
      'viewImages': 'Şəkilləri göstər',
      'monday': 'Bazar ertəsi',
      'tuesday': 'Çərşənbə axşamı',
      'wednesday': 'Çərşənbə',
      'thursday': 'Cümə axşamı',
      'friday': 'Cümə',
      'saturday': 'Şənbə',
      'sunday': 'Bazar',
      'daysOfWeek': 'Root günləri',
      'daysOfWeekSelection': 'Root günləri seçimi',
      'optimizeRoutes': 'Marşrutu optimallaşdır',
      'optimizationFinished': 'Optimizasiya bitdi!',
      'optimizationFailed': 'Optimizasiya zamanı xəta verdi!',
      'minDebt': 'Minimum Borc',
      'category': 'Kateqoriya',
      'server': 'Server',
      'chief': 'Satış müdiri',
      'firm': 'Firma',
      'categoryType': 'Kateqoriya tipi',
      'chooseCategoryType': 'Kateqoriya tipini seç',
      'chooseCategory': 'Kateqoriya seç',
      'categoryShort': 'Kat.',
      'weight': 'Çəki',
      'listPrice': 'List qiy.',
      'standPrice': 'Vitrin qiy.',
      'actionPrice': 'Aksiya qiy.',
      'save': 'Yadda saxla',
      'addComment': 'Şərh əlavə et',
      'newBenchmark': 'Yeni qiymətləndirmə',
      'countOfClients': 'Müştəri sayı',
      'view': 'Baxış',
      'report': 'Hesabat',
      'benchmarkShort': 'Qiymətl.',
      'monthly': 'Aylıq',
      'daily': 'Günlük',
      'dashboardReportForMonthly': 'Aylıq sənəd analizi',
      'dashboardReportForDaily': 'Günlük sənəd analizi',
      'lastDocDate': 'Sonuncu',
      'category1': 'Kategori 1',
      'category2': 'Kategori 2',
      'category1Selection': 'Kategori 1 seçimi',
      'category2Selection': 'Kategori 2 seçimi',
      'firmsSelection': 'Firma seçimi',
      'firms': 'Firmalar',
    },
    "tr": {
      "userName": "Kullanıcı",
      "password": "Şifre",
      "login": "Giriş Yap",
      "entry": "Giriş",
      "version": "Versiyon",
      "successful": "Başarılı",
      "usernameOrPasswordIsIncorrect": "Kullanıcı adı veya şifre yanlış!",
      "anErrorOccurred": "Bir hata oluştu!",
      "loginMismatch": "Giriş bilgilerinde uyumsuzluk tespit edildi!",
      "youDontHavePermission": "İzniniz yok",
      "language": "Dil",
      "logout": "Sistemden çıkış",
      "warning": "Uyarı",
      "ok": "Tamam",
      "details": "Detaylar",
      "attention": "Dikkat!",
      "yes": "Evet",
      "no": "Hayır",
      "search": "Ara",
      "az": "Azerice",
      "en": "İngilizce",
      "ru": "Rusça",
      "tr": "Türkçe",
      "about": "Hakkımızda",
      "close": "Kapat",
      "settings": "Ayarlar",
      "faq": "ChekList",
      "counting": "Araç Sayımı",
      "benchmark": "Fiyat Bankası",
      "confront": "Borç Karşılaştırması",
      "operations": "İşlemler",
      "code": "Kodu",
      "name": "Adı",
      "seller": "Satıcı",
      "distance": "Mesafe",
      "debt": "Borç",
      "lastConfrontDate": "Son Karşılaştırma",
      "list": "Liste",
      "map": "Harita",
      "all": "Hepsi",
      "errorGettingLocation": "Konum belirlenirken hata oluştu",
      "locationServicesAreDisabled":
          "Konum servisi devre dışı bırakıldı. Lütfen etkinleştirin",
      "locationPermissionsAreDenied": "Konum izinleri reddedildi!",
      "locationPermissionsArePermanentlyDenied":
          "Konum izinleri kalıcı olarak reddedildi!",
      "areYouSureYouWantToSave": "Kaydetmek istediğinizden emin misiniz?",
      "route": "Rota",
      "chaDocTypes1": "Kasa Tahsilat Makbuzu",
      "chaDocTypes2": "Kasa Ödeme Makbuzu",
      "chaDocTypes3": "Borç Dekontu",
      "chaDocTypes4": "Alacak Dekontu",
      "chaDocTypes5": "Virman Dekontu",
      "chaDocTypes6": "Kur Farkı",
      "chaDocTypes20": "Gelen Havale",
      "chaDocTypes21": "Gönderilen Havale",
      "chaDocTypes31": "Alış Faturası",
      "chaDocTypes32": "İade Faturası",
      "chaDocTypes33": "İade Faturası",
      "chaDocTypes37": "Satış Faturası",
      "chaDocTypes38": "Satış Faturası",
      "extra": "Hareketler",
      "total": "Tutar",
      "discount": "İndirim",
      "quantity": "Miktar",
      "price": "Fiyat",
      "areYouSureYouWantToDeleteThat": "Silmek istediğinizden emin misiniz?",
      "documentDeleted": "Belge silindi!",
      "clientDebt": "Borç",
      "confrontedDebt": "Karşılaştırılmış",
      "revise": "Değiştir",
      "delete": "Sil",
      "client": "Müşteri",
      "clientExtra": "Hareketleri",
      "clientConfronts": "Karşılaştırmaları",
      "docNumber": "Belge numarası",
      "newConfront": "Yeni Karşılaştırma",
      "isClientAgree": "Müşteri ile anlaşıldı mı?",
      "comment": "Yorum",
      "chooseClient": "Müşteri seç",
      "confrontTotal": "Karşılaştırma Tutarı",
      "documentSaved": "Belge kaydedildi",
      "clientNotSelected": "Müşteri seçilmedi!",
      "confrontDebtNotEntered": "Karşılaştırma tutarı girilmedi!",
      "choose": "Seç",
      "clientFilter": "Müşteri filtresi",
      "newFaq": "Yeni ChekList",
      "questions": "Sorular",
      "chooseFilter": "Filtre seç",
      "answer": "Cevap",
      "addImages": "Resim ekle",
      "takePhoto": "Kamera",
      "galery": "Galeri",
      "cancel": "İptal Et",
      "areYouSureYouWantToDeleteThisPhoto":
          "Bu resmi silmek istediğinizden emin misiniz?",
      "theQuestionDoesNotExistForThisClient":
          "Bu müşteri için soru mevcut değil!",
      "questionsMarkedWithStarCannotBeSkipped":
          "* ile işaretlenmiş sorular atlanamaz!",
      "print": "Yazdır",
      "newCounting": "Yeni Araç Sayımı",
      "car": "Araba",
      "chooseCar": "Araba seç",
      "quantityTyped": "Girilen sayımlar:",
      "onSystem": "Sistemde olan:",
      "totalCounted": "Toplam sayılan:",
      "counting_": "Sayım",
      "items": "Mallar",
      "subGroupless": "Alt grupsuz",
      "warehouseNotSelected": "Depo seçilmedi!",
      "noItemsOnList": "Listede mal yok!",
      "clientNotFound": "Müşteri bulunamadı!",
      "confrontShort": "Karşılaştırma",
      "type": "Tür",
      "viewImages": "Resimleri göster",
      "monday": "Pazartesi",
      "tuesday": "Salı",
      "wednesday": "Çarşamba",
      "thursday": "Perşembe",
      "friday": "Cuma",
      "saturday": "Cumartesi",
      "sunday": "Pazar",
      "daysOfWeek": "Rota günleri",
      "daysOfWeekSelection": "Rota günleri seçimi",
      "optimizeRoutes": "Rotayı optimize et",
      "optimizationFinished": "Optimizasyon bitti!",
      "optimizationFailed": "Optimizasyon sırasında hata oluştu!",
      "minDebt": "Minimum Borç",
      "category": "Kategori",
      "server": "Sunucu",
      "chief": "Satış müdürü",
      "firm": "Firma",
      "categoryType": "Kategori tipi",
      "chooseCategoryType": "Kategori tipini seç",
      "chooseCategory": "Kategori seç",
      "categoryShort": "Kat.",
      "weight": "Ağırlık",
      "listPrice": "Liste fiy.",
      "standPrice": "Vitrin fiy.",
      "actionPrice": "Aksiyon fiy.",
      "save": "Kaydet",
      "addComment": "Yorum ekle",
      "newBenchmark": "Yeni Değerlendirme",
      "countOfClients": "Müşteri sayısı",
      "view": "Görünüm",
      "report": "Rapor",
      "benchmarkShort": "Değerl.",
      "monthly": "Aylık",
      "daily": "Günlük",
      "dashboardReportForMonthly": "Aylık belge analizi",
      "dashboardReportForDaily": "Günlük belge analizi",
      "lastDocDate": "Sonuncu",
      "category1": "Kategori 1",
      "category2": "Kategori 2",
      "category1Selection": "Kategori 1 seçimi",
      "category2Selection": "Kategori 2 seçimi",
      "firmsSelection": "Firma seçimi",
      "firms": "Firmalar",
    },
    'en': {
      'userName': 'User',
      'password': 'Password',
      'login': 'Login',
      'entry': 'Entry',
      'version': 'Version',
      'successful': 'Successful',
      'usernameOrPasswordIsIncorrect': 'Username or password is incorrect!',
      'anErrorOccurred': 'An error occurred!',
      'loginMismatch': 'Login mismatch!',
      'youDontHavePermission': 'You don\'t have permission',
      'language': 'Language',
      'logout': 'Logout',
      'warning': 'Warning',
      'ok': 'Ok',
      'details': 'Details',
      'attention': 'Attention!',
      'yes': 'Yes',
      'no': 'No',
      'search': 'Search',
      'az': 'Azerbaijani',
      'en': 'English',
      'ru': 'Russian',
      'tr': 'Türkçe',
      'about': 'About',
      'close': 'Close',
      'settings': 'Settings',
      'faq': 'Faq',
      'counting': 'Counting',
      'benchmark': 'Benchmark',
      'confront': 'Confront',
      'operations': 'Operations',
      'code': 'Code',
      'name': 'Name',
      'seller': 'Seller',
      'distance': 'Distance',
      'debt': 'Debt',
      'lastConfrontDate': 'Last Confront Date',
      'list': 'List',
      'map': 'Map',
      'all': 'All',
      'errorGettingLocation': 'Error Getting Location',
      'locationServicesAreDisabled': 'Location Services Are Disabled',
      'locationPermissionsAreDenied': 'Location Permissions Are Denied',
      'locationPermissionsArePermanentlyDenied':
          'Location Permissions Are Permanently Denied',
      'areYouSureYouWantToSave': 'Are You Sure You Want To Save',
      'route': 'Route',
      'chaDocTypes1': 'Cha Doc Types1',
      'chaDocTypes2': 'Cha Doc Types2',
      'chaDocTypes3': 'Cha Doc Types3',
      'chaDocTypes4': 'Cha Doc Types4',
      'chaDocTypes5': 'Cha Doc Types5',
      'chaDocTypes6': 'Cha Doc Types6',
      'chaDocTypes20': 'Cha Doc Types20',
      'chaDocTypes21': 'Cha Doc Types21',
      'chaDocTypes31': 'Cha Doc Types31',
      'chaDocTypes32': 'Cha Doc Types32',
      'chaDocTypes33': 'Cha Doc Types33',
      'chaDocTypes37': 'Cha Doc Types37',
      'chaDocTypes38': 'Cha Doc Types38',
      'extra': 'Extra',
      'total': 'Total',
      'discount': 'Discount',
      'quantity': 'Quantity',
      'price': 'Price',
      'areYouSureYouWantToDeleteThat': 'Are You Sure You Want To Delete That',
      'documentDeleted': 'Document Deleted',
      'clientDebt': 'Client Debt',
      'confrontedDebt': 'Confronted Debt',
      'revise': 'Revise',
      'delete': 'Delete',
      'client': 'Client',
      'clientExtra': 'Client Extra',
      'clientConfronts': 'Client Confronts',
      'docNumber': 'Doc Number',
      'newConfront': 'New Confront',
      'category': 'Category',
      'server': 'Server',
      'chief': 'Sales Manager',
      'firm': 'Firm',
      'categoryType': 'Category Type',
      'chooseCategoryType': 'Choose Category Type',
      'chooseCategory': 'Choose Category',
      'categoryShort': 'Cat.',
      'weight': 'Weight',
      'listPrice': 'List Price',
      'standPrice': 'Stand Price',
      'actionPrice': 'Action Price',
      'save': 'Save',
      'addComment': 'Add Comment',
      'newBenchmark': 'New Benchmark',
      'countOfClients': 'Count of Clients',
      'view': 'View',
      'report': 'Report',
      'benchmarkShort': 'Benchmark',
      'monthly': 'Monthly',
      'daily': 'Daily',
      'dashboardReportForMonthly': 'Monthly Documents Report',
      'dashboardReportForDaily': 'Daily Documents Report',
      'counting_': 'Counting',
      'confrontShort': 'Confront',
      'lastDocDate': 'Last Doc',
      'category1': 'Category 1',
      'category2': 'Category 2',
      'category1Selection': 'Category 1 Selection',
      'category2Selection': 'Category 2 Selection',
      'firmsSelection': 'Firms Selection',
      'firms': 'Firms',
    },
    'ru': {
      'userName': 'Пользователь',
      'password': 'Пароль',
      'login': 'Войти',
      'entry': 'Вход',
      'version': 'Версия',
      'successful': 'Успешно',
      'usernameOrPasswordIsIncorrect': 'Имя пользователя или пароль неверны!',
      'anErrorOccurred': 'Произошла ошибка!',
      'loginMismatch': 'Несоответствие данных для входа!',
      'youDontHavePermission': 'У вас нет разрешения',
      'language': 'Язык',
      'logout': 'Выйти',
      'warning': 'Предупреждение',
      'ok': 'Ок',
      'details': 'Подробности',
      'attention': 'Внимание!',
      'yes': 'Да',
      'no': 'Нет',
      'search': 'Поиск',
      'az': 'Азербайджанский',
      'en': 'Английский',
      'ru': 'Русский',
      'tr': 'Турецкий',
      'about': 'О нас',
      'close': 'Закрыть',
      'settings': 'Настройки',
      'faq': 'ЧаВо',
      'counting': 'Подсчет',
      'benchmark': 'Сравнение',
      'confront': 'Сверка',
      'operations': 'Операции',
      'code': 'Код',
      'name': 'Имя',
      'seller': 'Продавец',
      'distance': 'Расстояние',
      'debt': 'Долг',
      'lastConfrontDate': 'Последняя сверка',
      'list': 'Список',
      'map': 'Карта',
      'all': 'Все',
      'errorGettingLocation': 'Ошибка получения местоположения',
      'locationServicesAreDisabled': 'Службы геолокации отключены',
      'locationPermissionsAreDenied': 'Разрешения на геолокацию отклонены',
      'locationPermissionsArePermanentlyDenied':
          'Разрешения на геолокацию отклонены навсегда',
      'areYouSureYouWantToSave': 'Вы уверены, что хотите сохранить?',
      'route': 'Маршрут',
      'chaDocTypes1': 'Типы документов Cha1',
      'chaDocTypes2': 'Типы документов Cha2',
      'chaDocTypes3': 'Типы документов Cha3',
      'chaDocTypes4': 'Типы документов Cha4',
      'chaDocTypes5': 'Типы документов Cha5',
      'chaDocTypes6': 'Типы документов Cha6',
      'chaDocTypes20': 'Типы документов Cha20',
      'chaDocTypes21': 'Типы документов Cha21',
      'chaDocTypes31': 'Типы документов Cha31',
      'chaDocTypes32': 'Типы документов Cha32',
      'chaDocTypes33': 'Типы документов Cha33',
      'chaDocTypes37': 'Типы документов Cha37',
      'chaDocTypes38': 'Типы документов Cha38',
      'extra': 'Дополнительно',
      'total': 'Всего',
      'discount': 'Скидка',
      'quantity': 'Количество',
      'price': 'Цена',
      'areYouSureYouWantToDeleteThat': 'Вы уверены, что хотите удалить это?',
      'documentDeleted': 'Документ удален',
      'clientDebt': 'Долг клиента',
      'confrontedDebt': 'Подтвержденный долг',
      'revise': 'Изменить',
      'delete': 'Удалить',
      'client': 'Клиент',
      'clientExtra': 'Дополнительно о клиенте',
      'clientConfronts': 'Сверки клиента',
      'docNumber': 'Номер документа',
      'newConfront': 'Новая сверка',
      'category': 'Категория',
      'server': 'Сервер',
      'chief': 'Руководитель отдела продаж',
      'firm': 'Фирма',
      'categoryType': 'Тип категории',
      'chooseCategoryType': 'Выберите тип категории',
      'chooseCategory': 'Выберите категорию',
      'categoryShort': 'Кат.',
      'weight': 'Вес',
      'listPrice': 'Прайс-лист',
      'standPrice': 'Цена на стенде',
      'actionPrice': 'Акционная цена',
      'save': 'Сохранить',
      'addComment': 'Добавить комментарий',
      'newBenchmark': 'Новое сравнение',
      'countOfClients': 'Количество клиентов',
      'view': 'Просмотр',
      'report': 'Отчет',
      'benchmarkShort': 'Сравнение',
      'monthly': 'Месяц',
      'daily': 'День',
      'dashboardReportForMonthly': 'Отчет по ежемесячным документам',
      'dashboardReportForDaily': 'Отчет по ежедневным документам',
      'counting_': 'Подсчет',
      'confrontShort': 'Сверка',
      'lastDocDate': 'Последняя',
      'category1': 'Категория 1',
      'category2': 'Категория 2',
      'category1Selection': 'Выбор категории 1',
      'category2Selection': 'Выбор категории 2',
      'firmsSelection': 'Выбор фирм',
      'firms': 'Фирмы',
    },
  };
  String getTranslatedText(String key) {
    String language = GlobalParams.language;
    return translations[language]?[key] ??
        translations['az']?[key] ??
        key; // Fallback
  }

  // get all keys
  List<String> getKeys() {
    return translations.keys.toList();
  }
}
